# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
include: [".htaccess"]

# Setup
title:               Public House
tagline:             No Tagline
url:                 https://thepublichouse.net
permalink:           /:year/:month/:day/:title
baseurl:             ""
author:              thepru

site_name: 'Public House'
site_url: 'https://thepublichouse.net'
copyright: '2020'

# Server Config options
livereload: true     # You no longer need to include --livereload